repository: fest/log-agent
variants:
  - tag: 2.0.3
    aliases:
      - :pike-{date}-{time}
    args:
      LOGSTASH_PLUGIN_BRANCH: v1.0.4
      JRUBY_VERSION: 9.1-alpine
      LOGSTASH_VERSION: 2.4-alpine
